### ISSUE TITLE
Profile picture inaccessible

### ISSUE THREAD

**Issue by mayaarguelles** [nyu-ossd-s19/yc2311-weekly#1]
the profile picture you chose is unable to be displayed cross-origin, so it is displaying an error image instead

**Comment by yc2311** [comment]
Thanks for pointing this out @mayaarguelles !

I saw this as an issue myself, and I believe it was because I could not find a fitting Staffordshire Bull Terrier picture as my avatar. I fixed the issue last week, but didn't remember closing the issue. Hopefully it works now.

**Comment by yc2311** [comment]
Also @mayaarguelles , now its a staffy reading a book in PJs
