### ISSUE TITLE
Fix wrong link

### ISSUE THREAD

**Issue by TrottPilgrim** [nyu-ossd-s19/yc2311-weekly#2]
https://github.com/nyu-ossd-s19/yc2311-weekly/blob/cff76b9f4182f7e41817420a7c27bc061ef0e305/_config.yml#L44 This should be updated to https://nyu-ossd-s19.github.io/yc2311-weekly . I think the 18 is probably because Joanna forgot to update the url

**Comment by yc2311** [comment]
You're absolutely right @TrottPilgrim 

Thanks for pointing this out! I'll fix it and close the issue.
